name: Update pending changes branch
description: Test

inputs:
  branch:
    description: "branch to run the composite action on."
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup git login
    run: |
      git config --global user.name "GitHub Actions Bot"
      git config --global user.email "<>"

  - name: Step 1
    run: |
      git fetch origin
      git checkout ${{inputs.branch}}
      git reset --hard origin/${{env.branch}}

  - name: Step 2
    run: git merge origin/master --no-edit --allow-unrelated-histories

  - name: Step 3
    run: git push -u origin ${{inputs.branch}}
