name: Update pending changes branch
description: Test

inputs:
  branch:
    description: "branch to run the composite action on."
    required: true

runs:
  using: "composite"
  steps:
  - name: Setup git login
    shell: cmd
    run: |
      git config --global user.name "GitHub Actions Bot"
      git config --global user.email "<>"

  - name: Step 1
    shell: cmd
    run: |
      git fetch origin
      git checkout ${{env.BRANCH}}
      git reset --hard origin/${{env.BRANCH}}

  - name: Step 2
    shell: cmd
    run: git merge origin/master --no-edit --allow-unrelated-histories

  - name: Step 3
    shell: cmd
    run: git push -u origin ${{env.BRANCH}}
