name: Update pending changes branch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      BRANCH: Test
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Test
      uses: ./.github/pending-changes-branch-composite/


